Bookstore: styling
Enekwestanley/bookstore-app-react pull request #5
Opened 2022-11-11 15:20 UTC by Enekwestanley

In this project we did the following:

-  Find all the details of the Bookstore design in [Zeplin](https://zeplin.io/).

- [Login to Zeplin](https://app.zeplin.io/login) (hint: you will find the credentials in the [sneak peek](https://github.com/microverseinc/curriculum-react-redux/blob/main/bookstore/sneak_peek_v2_0.md) of the project).

- Open the project Bookstore CMS.

- Use the information detailed in Zeplin to style the website.

- Your final design should match Zeplin's design.

2022-11-11 16:28 UTC, tresorsawasawa requested changes
# STATUS: REQUIRED CHANGES :recycle::recycle: 

Hi @Enekwestanley 
Good job so far! I know you worked hard to implement this project, I really appreciate the effort you put in! But there are some issues that you still need to work on to go to the next project but you are almost there! 

![almost-there](https://user-images.githubusercontent.com/57562869/143511358-9cde7daf-4ad0-4db2-8f15-18b54288ff91.gif)

## To highlight :champagne: 
- All linters are passing :heavy_check_mark: 
- Good commit history :heavy_check_mark: 
- Your design looks good :100: :heavy_check_mark: 
- Good PR description :heavy_check_mark: 
- Follow Gitflow :heavy_check_mark: 

## Required changes :recycle: :recycle: 
- [ ] Check the comments under the review.

## Optional suggestions

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

_Feel free to leave any questions or comments in the PR thread if something is not 100% clear. 
Please ping me [@tresorsawasawa](https://github.com/tresorsawasawa) when you comment so I can receive the notification or use slack with the same name._

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-11-11 16:28 UTC, tresorsawasawa commented on README.md
> +This is the last project of the Bookstore website. Now that all the functionality is done, you have to add styling. You will use Zeplin as a collaboration tool.
- [ **OPTIONAL** ] I think it would be better if you update your project description by proving a good one that tells about the whole project/application and not only describes this milestone(i.e. your description should tell about the whole application)

2022-11-11 16:28 UTC, tresorsawasawa commented on README.md
> +
- [ **OPTIONAL** ] To make your README looks better and professional, I think it would be better to update the live demo link to the below format/syntax.
```
[Live Demo](https://book-store-appp.netlify.app/) 
```

2022-11-11 16:28 UTC, tresorsawasawa commented on README.md
>  Clone the Repo and power on the live-server to view the App or click on the live demo link.
- [ **OPTIONAL** ] To make your README looks smart and professional I suggest you wrap each command line into **[backsticks](https://en.wikipedia.org/wiki/Backtick)**(**``**)e.g.: the cloning command,...
```
e.g.:
`git clone https://github.com/Enekwestanley/bookstore-app-react.git`
```

2022-11-11 16:28 UTC, tresorsawasawa commented on src/components/NavBar.css
> +
- [ ] Kindly make sure your header/menuNav sticks as much as possible to the one from the **[template design](https://app.zeplin.io/project/5b35a9e13227086040f8eb75/screen/5b695e29bb8c844f118f9378)**(e.g.: add elements on the header, use correct text_colors, spacing between and around elements, fonts(family, size. weight,...)...).
### Template design
![Screenshot from 2022-11-11 17-52-14](https://user-images.githubusercontent.com/83042742/201381761-7713d1f1-79ff-436f-81e3-fcd4d1348d6d.png)

### Your design
![Screenshot from 2022-11-11 18-02-13](https://user-images.githubusercontent.com/83042742/201381678-f463d52a-3c88-46e1-8da3-d7d678eb5f2f.png)

2022-11-11 16:28 UTC, tresorsawasawa commented on src/components/Book.css
>  .bookContainer {
- [ ] Kindly make sure each bookContainer block sticks as much as possible the template(e.g.: fonts, size, spacing,...) design for the project requirements.
### Template design
![Screenshot from 2022-11-11 18-08-07](https://user-images.githubusercontent.com/83042742/201383276-d3b9fe15-b9e8-4296-bb0c-8d2f66520461.png)

### Your design
![Screenshot from 2022-11-11 18-10-48](https://user-images.githubusercontent.com/83042742/201383329-b8535ab9-57e0-4c32-b116-e2912ad94757.png)

2022-11-11 16:28 UTC, tresorsawasawa commented on src/components/AddBook.css
>  }
- [ ] Kindly make sure your **formDiv** sticks as much as possible to the **[template design](https://app.zeplin.io/project/5b35a9e13227086040f8eb75/screen/5b695e29bb8c844f118f9378)**(e.g.: spacing between & around elements, text_colors, colors, alignments,...)

### Template design
![Screenshot from 2022-11-11 18-16-42](https://user-images.githubusercontent.com/83042742/201385409-db51029a-07b5-4ada-9c2f-95eeb3b31d41.png)

### Your design
![Screenshot from 2022-11-11 18-17-18](https://user-images.githubusercontent.com/83042742/201385542-297ed17f-88ae-43a7-9313-2018653202b8.png)

2022-11-12 02:34 UTC, BenMukebo requested changes
Hi @Enekwestanley, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

## To Highlight :clap: 
- No linter errors. :heavy_check_mark:
- Gitflow is followed. :heavy_check_mark:
- PR has a good title and summary. ✔️


 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏 💻  
Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please Tag me on (@BenMukebo) when you comment so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-11-12 02:34 UTC, BenMukebo commented on README.md
> +## [Live Demo](https://book-store-appp.netlify.app/)
- [OPTIONAL] I would also recommend adding the issue link in the contributing sections: 

```
## 🤝 Contributing

Contributions, issues, and feature requests are welcome!

Feel free to check the [issues page](../../issues/).
```

- [OPTIONAL] When I click the link to the `MIT.md` file that you added, I get this 404 `error`:

![00Mit](https://user-images.githubusercontent.com/79058364/182822618-fdfb2523-cb23-4060-9f72-75ec8c29e4cd.png)

- [OPTIONAL] Please update your Readme, it will be nice to add and update this section(`License`) with the type of License and a link to the license file, as this will make your readme more informative and professional. Checkout this [template](https://github.com/microverseinc/readme-template) for more clarifications.

2022-11-12 02:34 UTC, BenMukebo commented on src/components/Book.css
>  .bookContainer {
- [ ] As requested by the previous reviewer, Please make sure your styling is EXACTLY the same as the one provided on [Zeplin](https://zeplin.io/). Actually your your header, main and form sections do not have the the same widths let's correct this 👍🏻  

![Screenshot](https://user-images.githubusercontent.com/79058364/201452371-c9b60016-d350-4367-8b3d-0162c5f8cd79.png)

2022-11-12 06:32 UTC, Ismailco approved these changes
### Hi @Enekwestanley, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![cr-approve](https://user-images.githubusercontent.com/25227022/165483662-7b06c812-4cc0-40b9-a84c-4729d4cf10c3.gif)


## Highlights

✔️  No linter errors
✔️ Used Gitflow
✔️ Work documented professionally

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-11-12 06:41 UTC, merged